version: '3.8'

services:
  pipeline-app:
    image: mqcdev/as221s6_t09_crowchain:v3.0  
    container_name: pipeline_app
    ports:
      - "3000:3000"  
    restart: always  
    environment:
      - NEXT_PUBLIC_TEMPLATE_CLIENT_ID=4389436239beaeb4a86883310f4196a3  
      - CROWDFUNDING_FACTORY=0xf487e9e0A585C4900Ce25EA5b93386e7111ccD11
    command: ["npm", "run", "start"]  
